name: Upload data in Firebase

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt;
      - name: Create JSON file
        run: |
          echo '{"type": "service_account"}' > api-firebase.json
      - name: Test with pytest
        run: |
          python upload_to_firestore.py
